spring.application.name=outbox-publisher

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=eyp

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
